/*
 * XenLauncher
 * 
 * An open source Minecraft launcher. Work in progress.
 * Licenced under the GNU General Public License, version 2 - http://www.gnu.org/licenses/gpl-2.0.html
 * Created by Benjamin Gwynn (http://xenxier.tk)
 */

/**
 * @name XenLauncher
 * @author xenxier
 */

/*

WARNING!

The vast majority of this code has been generated by NetBeans. However,
some code has been added/modified. This code is not clean, but will be cleaned
up to seperate the generated code from the modified code.

** DO NOT EDIT THIS CODE **

*/

// <editor-fold defaultstate="collapsed" desc="Unclean (mostly generated) Code.">

package xenlauncher;

import java.awt.Component;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Random;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.eclipse.jgit.api.errors.GitAPIException;
import org.eclipse.jgit.api.errors.InvalidRefNameException;
import org.eclipse.jgit.api.errors.JGitInternalException;
import org.eclipse.jgit.api.errors.RefNotFoundException;

public class LauncherGUI extends javax.swing.JFrame {
    public LauncherGUI() {
        initComponents();
        ver.setText(meta.getFullVersionInformation());
        rand.setText(createRandomSplash());
        newInfoText("XenLauncher Ready. Created by Benjamin Gwynn.");
        updateRepositoryInformation(repositorySelector.getSelectedItem().toString());
        repoBranchField.setText(meta.getVersionName().toLowerCase());
    }
    
    final void updateRepositorySelectorList() {
        Output.print('I', "Updating Repository Selector list...");
        repositorySelector.addItem(RepositoryDatabase.selectRepo(RepositoryDatabase.getListOfRepoNames().size() - 1));
        repositorySelector.revalidate();
        repositorySelector.updateUI();
    }
    
    private void updateRepositoryInformation(String repo_name) {
        repoInformationText.setText(null);
        try {
            List<String> line = RepositoryDatabase.getRepositoryMeta(repo_name, "repo_information");
            for (int i = 0; i < line.size(); i++) {
                repoInformationText.setText(repoInformationText.getText() + line.get(i) + "\n");
            }
        } catch (FileNotFoundException ex) {
            Output.error("Cannot get information. Information missing. (Java FileNotFoundException)", ex);
        } catch (IOException ex) {
            Output.error("Cannot get information. (Java IOException)", ex);
        }
    }
    
    public void setProgressBar(int percentage) {
        primaryProgressBar.setValue(primaryProgressBar.getWidth() * (percentage / 100));
        primaryProgressBar.updateUI();
    }
    
    public final void newInfoText(String text) {
        info_text.setText(text);
        info_text.updateUI();
    }
    
    public void showError(String msg) {
        //if (errorDialog.isVisible()) {
        //    errorDialog.setVisible(false);
        //}
        errorDialogErrorText.setText(msg);
        errorDialog.setVisible(true);
    }
    
    public void writeToLog(char type, String msg) {
        if ('E' == type) {
            switchToErrorTab();
        }
        if (guiLogText.getText().isEmpty()) {
            guiLogText.setText(msg + "\n");
        } else {
            guiLogText.setText(guiLogText.getText() + "\n" + msg + "\n");
        }
        guiLogText.updateUI();
    }
    
    private void switchToErrorTab() {
        this.switchTab(this.errorReportContainer);
    }
    
    private void switchTab(Component tab) {
        launcherTabs.setSelectedComponent(tab);
        launcherTabs.requestFocus();
        tab.requestFocus();
    }
    
    private static String createRandomSplash() {
        ArrayList splashList = new ArrayList();
        splashList.add("Written in Java!");
        splashList.add("Python-free!");
        splashList.add("Free to use!");
        splashList.add("Turtles!");
        splashList.add("Skeletons are OP.");
        splashList.add("Death by Java.");
        splashList.add("A work-in-progress.");
        splashList.add("Oops, typo.");
        splashList.add("Random text!");
        splashList.add("Spooky scary skeletons.");
        splashList.add("Nyan Cats!");
        splashList.add("Speedy thing goes in, speedy thing comes out.");
        splashList.add("Make it rain!");
        splashList.add("Open Source all the things!");
        splashList.add("Git powered!");
        splashList.add("1.7 Compatible!");
        splashList.add(String.valueOf(splashList.size() + 1) + " possible splashes!");
        return String.valueOf(splashList.get(new Random().nextInt(splashList.size())));
    }

    /**
    
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingsFrame = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        closeSettingsButton = new javax.swing.JButton();
        launch_selection = new javax.swing.ButtonGroup();
        repoManagerFrame = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        closeRepoManagerButton = new javax.swing.JButton();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel13 = new javax.swing.JLabel();
        openAddRepoDialogButton = new javax.swing.JButton();
        repositorySelector = new javax.swing.JComboBox(RepositoryDatabase.getListOfRepoNames().toArray());
        jScrollPane1 = new javax.swing.JScrollPane();
        repoInformationText = new javax.swing.JTextPane();
        removeRepoButton = new javax.swing.JButton();
        errorDialog = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        closeErrorDialog = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        errorDialogErrorText = new javax.swing.JTextArea();
        addRepoDialog = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        repoNameField = new javax.swing.JTextField();
        addRepoButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        repoURLField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        repoBranchField = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        launchButton = new javax.swing.JButton();
        primaryProgressBar = new javax.swing.JProgressBar();
        username = new javax.swing.JTextField();
        rand = new javax.swing.JLabel();
        ver = new javax.swing.JLabel();
        info_text = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        settingsButton = new javax.swing.JButton();
        repoManagerButton = new javax.swing.JButton();
        launcherTabs = new javax.swing.JTabbedPane();
        webPaneContainer = new javax.swing.JScrollPane();
        webPane = new javax.swing.JEditorPane();
        modpackPaneContainer = new javax.swing.JScrollPane();
        modpackPane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        errorReportContainer = new javax.swing.JScrollPane();
        guiLogText = new javax.swing.JTextPane();
        forceUpdateButton = new javax.swing.JToggleButton();
        tempButton = new javax.swing.JButton();

        settingsFrame.setTitle("Settings");
        settingsFrame.setAlwaysOnTop(true);
        settingsFrame.setMinimumSize(new java.awt.Dimension(452, 471));
        settingsFrame.setName("SettingsFrame"); // NOI18N
        settingsFrame.setResizable(false);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel5.setText("XenLauncher Settings");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel6.setText("Security");

        jLabel7.setText("You may choose to disable authentication to Mojang at login.");

        jLabel8.setText("Although this enables users to login without an active internet");

        jLabel9.setText("connection, this also disables the user from downloading new");

        jLabel10.setText("Minecraft versions and being able to connect to 'online mode'");

        jLabel11.setText("servers. Your skin may also fail to load.");

        jLabel12.setText("This does not affect mod downloading or repo updating.");

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Authenticate to Mojang on login");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        closeSettingsButton.setText("Close");
        closeSettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeSettingsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout settingsFrameLayout = new javax.swing.GroupLayout(settingsFrame.getContentPane());
        settingsFrame.getContentPane().setLayout(settingsFrameLayout);
        settingsFrameLayout.setHorizontalGroup(
            settingsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(settingsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(closeSettingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(settingsFrameLayout.createSequentialGroup()
                        .addGroup(settingsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jCheckBox1))
                        .addGap(0, 12, Short.MAX_VALUE))))
        );
        settingsFrameLayout.setVerticalGroup(
            settingsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(7, 7, 7)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(closeSettingsButton)
                .addContainerGap())
        );

        repoManagerFrame.setTitle("Repo Manager");
        repoManagerFrame.setMinimumSize(new java.awt.Dimension(600, 400));
        repoManagerFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                repoManagerFrameWindowOpened(evt);
            }
        });
        repoManagerFrame.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                repoManagerFrameMouseMoved(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel4.setText("Repo Manager");

        closeRepoManagerButton.setText("Close");
        closeRepoManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeRepoManagerButtonActionPerformed(evt);
            }
        });

        jLabel13.setText("Repository Name:");

        openAddRepoDialogButton.setText("Add a repo");
        openAddRepoDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openAddRepoDialogButtonActionPerformed(evt);
            }
        });

        repositorySelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repositorySelectorActionPerformed(evt);
            }
        });
        repositorySelector.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                repositorySelectorFocusLost(evt);
            }
        });

        repoInformationText.setText("Placeholder");
        jScrollPane1.setViewportView(repoInformationText);

        removeRepoButton.setText("Remove this Repo");
        removeRepoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeRepoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout repoManagerFrameLayout = new javax.swing.GroupLayout(repoManagerFrame.getContentPane());
        repoManagerFrame.getContentPane().setLayout(repoManagerFrameLayout);
        repoManagerFrameLayout.setHorizontalGroup(
            repoManagerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(repoManagerFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(repoManagerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(repoManagerFrameLayout.createSequentialGroup()
                        .addGroup(repoManagerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(repoManagerFrameLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(repositorySelector, 0, 256, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeRepoButton))
                            .addComponent(jScrollPane1)
                            .addGroup(repoManagerFrameLayout.createSequentialGroup()
                                .addComponent(jProgressBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(closeRepoManagerButton))
                            .addGroup(repoManagerFrameLayout.createSequentialGroup()
                                .addGroup(repoManagerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(openAddRepoDialogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        repoManagerFrameLayout.setVerticalGroup(
            repoManagerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(repoManagerFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(repoManagerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(repositorySelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeRepoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openAddRepoDialogButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(repoManagerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(closeRepoManagerButton)
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        errorDialog.setTitle("Oops");
        errorDialog.setAlwaysOnTop(true);
        errorDialog.setMinimumSize(new java.awt.Dimension(402, 210));
        errorDialog.setResizable(false);

        jLabel15.setText("Oops. Something went awry.");

        closeErrorDialog.setText("Okay");
        closeErrorDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeErrorDialogActionPerformed(evt);
            }
        });

        errorDialogErrorText.setColumns(20);
        errorDialogErrorText.setLineWrap(true);
        errorDialogErrorText.setRows(5);
        jScrollPane2.setViewportView(errorDialogErrorText);

        javax.swing.GroupLayout errorDialogLayout = new javax.swing.GroupLayout(errorDialog.getContentPane());
        errorDialog.getContentPane().setLayout(errorDialogLayout);
        errorDialogLayout.setHorizontalGroup(
            errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                    .addGroup(errorDialogLayout.createSequentialGroup()
                        .addGroup(errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(closeErrorDialog))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        errorDialogLayout.setVerticalGroup(
            errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeErrorDialog)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        addRepoDialog.setTitle("Add Repository");
        addRepoDialog.setMaximumSize(new java.awt.Dimension(450, 170));
        addRepoDialog.setMinimumSize(new java.awt.Dimension(450, 170));
        addRepoDialog.setPreferredSize(new java.awt.Dimension(450, 170));
        addRepoDialog.setResizable(false);
        addRepoDialog.setType(java.awt.Window.Type.UTILITY);

        jLabel14.setText("Repository Name:");

        addRepoButton.setText("Add Repository");
        addRepoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRepoButtonActionPerformed(evt);
            }
        });

        jLabel16.setText("Repository Git URL:");

        jLabel17.setText("Repository Branch:");

        repoBranchField.setEditable(false);
        repoBranchField.setText("hydrogen");
        repoBranchField.setEnabled(false);

        javax.swing.GroupLayout addRepoDialogLayout = new javax.swing.GroupLayout(addRepoDialog.getContentPane());
        addRepoDialog.getContentPane().setLayout(addRepoDialogLayout);
        addRepoDialogLayout.setHorizontalGroup(
            addRepoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRepoDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addRepoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addRepoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(addRepoDialogLayout.createSequentialGroup()
                        .addGroup(addRepoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addRepoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(repoBranchField, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(repoNameField)
                            .addComponent(repoURLField))))
                .addContainerGap())
        );
        addRepoDialogLayout.setVerticalGroup(
            addRepoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRepoDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addRepoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(repoNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addRepoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(repoURLField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addRepoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(repoBranchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(addRepoButton)
                .addContainerGap())
        );

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("XenLauncher");
        setBackground(new java.awt.Color(229, 229, 229));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Ubuntu Light", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("XenLauncher");
        jLabel1.setFocusable(false);
        jLabel1.setRequestFocusEnabled(false);

        launchButton.setText("Launch");
        launchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launchButtonActionPerformed(evt);
            }
        });

        username.setText("Username");
        username.setToolTipText("Username");
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
        });

        rand.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        rand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rand.setText("Loading...");

        ver.setText("Couldn't get Version");

        info_text.setText("Loading...");

        jLabel2.setText("0 Repos loaded. Everything up to date.");

        password.setText("fishisabadpassword");

        settingsButton.setText("Settings");
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });

        repoManagerButton.setText("Repo Manager");
        repoManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repoManagerButtonActionPerformed(evt);
            }
        });

        launcherTabs.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        webPane.setEditable(false);
        webPane.setAlignmentX(0.0F);
        webPane.setAlignmentY(0.0F);
        webPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        webPane.setMargin(new java.awt.Insets(0, 0, 0, 0));
        webPaneContainer.setViewportView(webPane);

        launcherTabs.addTab("Minecraft Updates", webPaneContainer);

        modpackPaneContainer.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        modpackPaneContainer.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        modpackPaneContainer.setPreferredSize(new java.awt.Dimension(40, 100));

        jLabel3.setText("Work in progress");

        javax.swing.GroupLayout modpackPaneLayout = new javax.swing.GroupLayout(modpackPane);
        modpackPane.setLayout(modpackPaneLayout);
        modpackPaneLayout.setHorizontalGroup(
            modpackPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modpackPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(704, Short.MAX_VALUE))
        );
        modpackPaneLayout.setVerticalGroup(
            modpackPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modpackPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(330, Short.MAX_VALUE))
        );

        modpackPaneContainer.setViewportView(modpackPane);

        launcherTabs.addTab("Modpack Manager", modpackPaneContainer);

        guiLogText.setEditable(false);
        guiLogText.setToolTipText("Error Log");
        guiLogText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        errorReportContainer.setViewportView(guiLogText);
        guiLogText.getAccessibleContext().setAccessibleName("Error Log");

        launcherTabs.addTab("Error Report", errorReportContainer);

        forceUpdateButton.setText("Force Update");

        tempButton.setText("Test ");
        tempButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(launcherTabs, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(primaryProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(forceUpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tempButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(settingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(repoManagerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(launchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(info_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(launcherTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(info_text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(repoManagerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tempButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(settingsButton)
                            .addComponent(forceUpdateButton)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(launchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(primaryProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ver, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        username.setText(null);
    }//GEN-LAST:event_usernameFocusGained

    private void launchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchButtonActionPerformed
        new LaunchGame().LaunchGameEvent(username.getText());
    }//GEN-LAST:event_launchButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        settingsFrame.setVisible(true);
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void repoManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repoManagerButtonActionPerformed
        repoManagerFrame.setVisible(true);
    }//GEN-LAST:event_repoManagerButtonActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void closeSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeSettingsButtonActionPerformed
        settingsFrame.setVisible(false);
    }//GEN-LAST:event_closeSettingsButtonActionPerformed

    private void closeRepoManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeRepoManagerButtonActionPerformed
        repoManagerFrame.setVisible(false);
    }//GEN-LAST:event_closeRepoManagerButtonActionPerformed

    private void closeErrorDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeErrorDialogActionPerformed
        errorDialog.setVisible(false);
    }//GEN-LAST:event_closeErrorDialogActionPerformed

    private void openAddRepoDialogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openAddRepoDialogButtonActionPerformed
        addRepoDialog.setVisible(true);
    }//GEN-LAST:event_openAddRepoDialogButtonActionPerformed

    private void tempButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempButtonActionPerformed
        // ***** TEMP ERROR BUTTON *****
        Output.error("Something bad happened.");
        new LauncherGUI().switchToErrorTab();
        newInfoText("Hello there newInfoText!");
    }//GEN-LAST:event_tempButtonActionPerformed

    private void repositorySelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repositorySelectorActionPerformed
        updateRepositoryInformation(repositorySelector.getSelectedItem().toString());
        if (repositorySelector.getSelectedItem().equals("XenLauncher Default Repository")) {
            removeRepoButton.setEnabled(false);
        } else {
            removeRepoButton.setEnabled(true);
        }
    }//GEN-LAST:event_repositorySelectorActionPerformed

    private void addRepoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRepoButtonActionPerformed
        try {
            RepositoryDatabase.addRepo(repoNameField.getText(), repoURLField.getText());
            updateRepositorySelectorList();
        } catch (IOException ex) {
            Output.error("Cannot create the repo. Maybe you don't have permission to write here? (Java IOException)", ex);
        } catch (JGitInternalException ex) {
            Output.error("Cannot create the repo. Maybe the repo already exists but XenLauncher didn't see it? (Java JGitInternelException)", ex);
        } catch (RefNotFoundException ex) {
            Output.error("Cannot create the repo. Reference not found. Outdated repo? (Java RefNotFoundException)", ex);
            RepositoryDatabase.removeRepositoryFolderCatch(repoNameField.getText());
        } catch (InvalidRefNameException ex) {
            Output.error("Cannot create the repo. Not a Git repo. (Java InvalidRefNameException)", ex);
            RepositoryDatabase.removeRepositoryFolderCatch(repoNameField.getText());
        } catch (GitAPIException ex) {
            Output.error("Cannot create the repo. API Error. Bad Git repo? (Java GitAPIException)", ex);
            RepositoryDatabase.removeRepositoryFolderCatch(repoNameField.getText());
        }
        addRepoDialog.setVisible(false);
    }//GEN-LAST:event_addRepoButtonActionPerformed

    private void removeRepoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeRepoButtonActionPerformed
        try {
            RepositoryDatabase.removeRepository(repositorySelector.getSelectedItem().toString());
            repositorySelector.removeItem(repositorySelector.getSelectedItem());
            repositorySelector.setSelectedIndex(0);
        } catch (Exception ex) {
            Output.error("Coudln't remove repository. (Vague Java exception)", ex);
        }
    }//GEN-LAST:event_removeRepoButtonActionPerformed

    private void repositorySelectorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_repositorySelectorFocusLost

    }//GEN-LAST:event_repositorySelectorFocusLost

    private void repoManagerFrameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repoManagerFrameMouseMoved

    }//GEN-LAST:event_repoManagerFrameMouseMoved

    private void repoManagerFrameWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_repoManagerFrameWindowOpened
        if (repositorySelector.getSelectedItem().equals("XenLauncher Default Repository")) {
            removeRepoButton.setEnabled(false);
        } else {
            removeRepoButton.setEnabled(true);
        }
    }//GEN-LAST:event_repoManagerFrameWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LauncherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LauncherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LauncherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LauncherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LauncherGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRepoButton;
    private javax.swing.JDialog addRepoDialog;
    private javax.swing.JButton closeErrorDialog;
    private javax.swing.JButton closeRepoManagerButton;
    private javax.swing.JButton closeSettingsButton;
    private javax.swing.JDialog errorDialog;
    private javax.swing.JTextArea errorDialogErrorText;
    private javax.swing.JScrollPane errorReportContainer;
    private javax.swing.JToggleButton forceUpdateButton;
    private javax.swing.JTextPane guiLogText;
    private javax.swing.JLabel info_text;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton launchButton;
    private javax.swing.ButtonGroup launch_selection;
    private javax.swing.JTabbedPane launcherTabs;
    private javax.swing.JPanel modpackPane;
    private javax.swing.JScrollPane modpackPaneContainer;
    private javax.swing.JButton openAddRepoDialogButton;
    private javax.swing.JPasswordField password;
    private javax.swing.JProgressBar primaryProgressBar;
    private javax.swing.JLabel rand;
    private javax.swing.JButton removeRepoButton;
    private javax.swing.JTextField repoBranchField;
    private javax.swing.JTextPane repoInformationText;
    private javax.swing.JButton repoManagerButton;
    private javax.swing.JFrame repoManagerFrame;
    private javax.swing.JTextField repoNameField;
    private javax.swing.JTextField repoURLField;
    private javax.swing.JComboBox repositorySelector;
    private javax.swing.JButton settingsButton;
    private javax.swing.JFrame settingsFrame;
    private javax.swing.JButton tempButton;
    private javax.swing.JTextField username;
    private javax.swing.JLabel ver;
    private javax.swing.JEditorPane webPane;
    private javax.swing.JScrollPane webPaneContainer;
    // End of variables declaration//GEN-END:variables
}

// </editor-fold>