/*
 * XenLauncher
 * 
 * An open source Minecraft launcher. Work in progress.
 * Licenced under the GNU General Public License, version 2 - http://www.gnu.org/licenses/gpl-2.0.html
 * Created by Benjamin Gwynn (http://xenxier.tk)
 */

/**
 * @name XenLauncher
 * @author xenxier
 */

/*

WARNING!

The vast majority of this code has been generated by NetBeans. However,
some code has been added/modified. This code is not clean, but will be cleaned
up to seperate the generated code from the modified code.

** DO NOT EDIT THIS CODE **

*/

package xenlauncher;

import java.awt.Component;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

public class LauncherGUI extends javax.swing.JFrame {

    public LauncherGUI() {
        initComponents();
        ver.setText(meta.getFullVersionInformation());
        rand.setText(createRandomSplash());
        
        try {
            URL url = new URL("http://mcupdate.tumblr.com/");
            webPane.setPage(url);
        } catch (MalformedURLException ex) {
            webPane.setText("Java threw MalformedURLException - is your internet connection down or are you using XenLauncher on a toaster?");
            Logger.getLogger(LauncherGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            webPane.setText("Java threw IOException - is your internet connection down?");
            Logger.getLogger(LauncherGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void newInfoText(String text) {
        Output.print('D', "newInfoText got " + text);
        info_text.setText(text);
    }
    
    public void refreshGUI() {
        Output.print('D', "Refreshing GUI.");
        revalidate();
        repaint();
        getContentPane().validate();
        getContentPane().repaint();
    }
    
    public void showError(String msg) {
        if (errorDialog.isVisible()) {
            errorDialog.setVisible(false);
        }
        errorDialogErrorText.setText(msg);
        errorDialog.setVisible(true);
    }
    
    public void writeToLog(char type, String msg) {
        if ('E' == type) {
            switchToErrorTab();
        }
        if (guiLogText.getText().isEmpty()) {
            guiLogText.setText(msg + "\n");
        } else {
            guiLogText.setText(guiLogText.getText() + "\n" + msg + "\n");
        }
        guiLogText.revalidate();
        guiLogText.repaint();
    }
    
    private void switchToErrorTab() {
        this.switchTab(this.errorReportContainer);
    }
    
    private void switchTab(Component tab) {
        launcherTabs.setSelectedComponent(tab);
        launcherTabs.requestFocus();
        tab.requestFocus();
    }
    
    private static String createRandomSplash() {
        ArrayList splashList = new ArrayList();
        splashList.add("Written in Java!");
        splashList.add("Python-free!");
        splashList.add("Free to use!");
        splashList.add("Turtles!");
        splashList.add("Skeletons are OP.");
        splashList.add("Death by Java.");
        splashList.add("A work-in-progress.");
        splashList.add("Oops, typo.");
        splashList.add("Random text!");
        splashList.add("Spooky scary skeletons.");
        splashList.add("Nyan Cats!");
        splashList.add("Speedy thing goes in, speedy thing comes out.");
        splashList.add("Make it rain!");
        splashList.add("Open Source all the things!");
        splashList.add(String.valueOf(splashList.size() + 1) + " possible splashes!");
        return String.valueOf(splashList.get(new Random().nextInt(splashList.size())));
    }

    /**
    
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingsFrame = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        closeSettingsButton = new javax.swing.JButton();
        launch_selection = new javax.swing.ButtonGroup();
        repoManagerFrame = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        closeRepoManagerButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel13 = new javax.swing.JLabel();
        openRepoManagerAddRepoFrameButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        repoBox = new javax.swing.JTextPane();
        repoManagerAddRepoFrame = new javax.swing.JFrame();
        jLabel14 = new javax.swing.JLabel();
        addRepoButton = new javax.swing.JButton();
        addRepoInput = new javax.swing.JTextField();
        errorDialog = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        errorDialogErrorText = new javax.swing.JLabel();
        closeErrorDialog = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        launch = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        username = new javax.swing.JTextField();
        rand = new javax.swing.JLabel();
        ver = new javax.swing.JLabel();
        info_text = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        settingsButton = new javax.swing.JButton();
        repoManagerButton = new javax.swing.JButton();
        launcherTabs = new javax.swing.JTabbedPane();
        webPaneContainer = new javax.swing.JScrollPane();
        webPane = new javax.swing.JEditorPane();
        modpackPaneContainer = new javax.swing.JScrollPane();
        modpackPane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        errorReportContainer = new javax.swing.JScrollPane();
        guiLogText = new javax.swing.JTextPane();
        jToggleButton1 = new javax.swing.JToggleButton();
        tempButton = new javax.swing.JButton();

        settingsFrame.setTitle("Settings");
        settingsFrame.setAlwaysOnTop(true);
        settingsFrame.setMinimumSize(new java.awt.Dimension(452, 471));
        settingsFrame.setName("SettingsFrame"); // NOI18N
        settingsFrame.setResizable(false);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel5.setText("XenLauncher Settings");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel6.setText("Security");

        jLabel7.setText("You may choose to disable authentication to Mojang at login.");

        jLabel8.setText("Although this enables users to login without an active internet");

        jLabel9.setText("connection, this also disables the user from downloading new");

        jLabel10.setText("Minecraft versions and being able to connect to 'online mode'");

        jLabel11.setText("servers. Your skin may also fail to load.");

        jLabel12.setText("This does not affect mod downloading or repo updating.");

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Authenticate to Mojang on login");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        closeSettingsButton.setText("Close");
        closeSettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeSettingsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout settingsFrameLayout = new javax.swing.GroupLayout(settingsFrame.getContentPane());
        settingsFrame.getContentPane().setLayout(settingsFrameLayout);
        settingsFrameLayout.setHorizontalGroup(
            settingsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(settingsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(closeSettingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(settingsFrameLayout.createSequentialGroup()
                        .addGroup(settingsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jCheckBox1))
                        .addGap(0, 12, Short.MAX_VALUE))))
        );
        settingsFrameLayout.setVerticalGroup(
            settingsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(7, 7, 7)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(closeSettingsButton)
                .addContainerGap())
        );

        repoManagerFrame.setTitle("Repo Manager");
        repoManagerFrame.setMinimumSize(new java.awt.Dimension(600, 400));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel4.setText("Repo Manager");

        closeRepoManagerButton.setText("Close");
        closeRepoManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeRepoManagerButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Advanced Settings [WIP]");

        jLabel13.setText("Work in progress. Advanced settings not ready yet.");

        openRepoManagerAddRepoFrameButton.setText("Add a repo");
        openRepoManagerAddRepoFrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openRepoManagerAddRepoFrameButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(repoBox);

        javax.swing.GroupLayout repoManagerFrameLayout = new javax.swing.GroupLayout(repoManagerFrame.getContentPane());
        repoManagerFrame.getContentPane().setLayout(repoManagerFrameLayout);
        repoManagerFrameLayout.setHorizontalGroup(
            repoManagerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(repoManagerFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(repoManagerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addGroup(repoManagerFrameLayout.createSequentialGroup()
                        .addComponent(jProgressBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeRepoManagerButton))
                    .addGroup(repoManagerFrameLayout.createSequentialGroup()
                        .addGroup(repoManagerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel13)
                            .addComponent(openRepoManagerAddRepoFrameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        repoManagerFrameLayout.setVerticalGroup(
            repoManagerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(repoManagerFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openRepoManagerAddRepoFrameButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(repoManagerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(repoManagerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(closeRepoManagerButton)
                        .addComponent(jButton2))
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        repoManagerAddRepoFrame.setTitle("Add Repo");
        repoManagerAddRepoFrame.setMinimumSize(new java.awt.Dimension(399, 89));
        repoManagerAddRepoFrame.setResizable(false);

        jLabel14.setText("Add Repo");

        addRepoButton.setText("Add");
        addRepoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRepoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout repoManagerAddRepoFrameLayout = new javax.swing.GroupLayout(repoManagerAddRepoFrame.getContentPane());
        repoManagerAddRepoFrame.getContentPane().setLayout(repoManagerAddRepoFrameLayout);
        repoManagerAddRepoFrameLayout.setHorizontalGroup(
            repoManagerAddRepoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(repoManagerAddRepoFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(repoManagerAddRepoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(repoManagerAddRepoFrameLayout.createSequentialGroup()
                        .addComponent(addRepoInput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addRepoButton))
                    .addGroup(repoManagerAddRepoFrameLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 312, Short.MAX_VALUE)))
                .addContainerGap())
        );
        repoManagerAddRepoFrameLayout.setVerticalGroup(
            repoManagerAddRepoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(repoManagerAddRepoFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(repoManagerAddRepoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRepoButton)
                    .addComponent(addRepoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        errorDialog.setMinimumSize(new java.awt.Dimension(400, 152));
        errorDialog.setResizable(false);

        jLabel15.setText("Oops. Something went awry.");

        errorDialogErrorText.setText("Error placeholder");

        closeErrorDialog.setText("Okay");
        closeErrorDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeErrorDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout errorDialogLayout = new javax.swing.GroupLayout(errorDialog.getContentPane());
        errorDialog.getContentPane().setLayout(errorDialogLayout);
        errorDialogLayout.setHorizontalGroup(
            errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(closeErrorDialog)
                    .addComponent(errorDialogErrorText))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        errorDialogLayout.setVerticalGroup(
            errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorDialogErrorText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(closeErrorDialog)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("XenLauncher");
        setBackground(new java.awt.Color(229, 229, 229));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Ubuntu Light", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("XenLauncher");
        jLabel1.setFocusable(false);
        jLabel1.setRequestFocusEnabled(false);

        launch.setText("Launch");
        launch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launchActionPerformed(evt);
            }
        });

        username.setText("Username");
        username.setToolTipText("Username");
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
        });

        rand.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        rand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rand.setText("No random splash for you.");

        ver.setText("Couldn't get Version");

        info_text.setText("Welcome to XenLauncher. Created by Benjamin Gwynn.");

        jLabel2.setText("0 Repos loaded. Everything up to date.");

        password.setText("fishisabadpassword");

        settingsButton.setText("Settings");
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });

        repoManagerButton.setText("Repo Manager");
        repoManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repoManagerButtonActionPerformed(evt);
            }
        });

        launcherTabs.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        webPane.setEditable(false);
        webPane.setText("Couldn't change text - is your internet connection down?");
        webPane.setAlignmentX(0.0F);
        webPane.setAlignmentY(0.0F);
        webPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        webPane.setMargin(new java.awt.Insets(0, 0, 0, 0));
        webPaneContainer.setViewportView(webPane);

        launcherTabs.addTab("Minecraft Updates", webPaneContainer);

        modpackPaneContainer.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        modpackPaneContainer.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        modpackPaneContainer.setPreferredSize(new java.awt.Dimension(40, 100));

        jLabel3.setText("Work in progress");

        javax.swing.GroupLayout modpackPaneLayout = new javax.swing.GroupLayout(modpackPane);
        modpackPane.setLayout(modpackPaneLayout);
        modpackPaneLayout.setHorizontalGroup(
            modpackPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modpackPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(704, Short.MAX_VALUE))
        );
        modpackPaneLayout.setVerticalGroup(
            modpackPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modpackPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(330, Short.MAX_VALUE))
        );

        modpackPaneContainer.setViewportView(modpackPane);

        launcherTabs.addTab("Modpack Manager", modpackPaneContainer);

        guiLogText.setEditable(false);
        guiLogText.setToolTipText("Error Log");
        guiLogText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        errorReportContainer.setViewportView(guiLogText);
        guiLogText.getAccessibleContext().setAccessibleName("Error Log");

        launcherTabs.addTab("Error Report", errorReportContainer);

        jToggleButton1.setText("Force Update");

        tempButton.setText("Test ");
        tempButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(launcherTabs, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tempButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(settingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(repoManagerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(launch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(info_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(launcherTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(info_text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(repoManagerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tempButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(settingsButton)
                            .addComponent(jToggleButton1)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(launch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ver, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        username.setText(null);
    }//GEN-LAST:event_usernameFocusGained

    private void launchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchActionPerformed
        new LaunchGame().LaunchGameEvent(username.getText());
    }//GEN-LAST:event_launchActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        settingsFrame.setVisible(true);
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void repoManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repoManagerButtonActionPerformed
        repoManagerFrame.setVisible(true);
    }//GEN-LAST:event_repoManagerButtonActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void closeSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeSettingsButtonActionPerformed
        settingsFrame.setVisible(false);
    }//GEN-LAST:event_closeSettingsButtonActionPerformed

    private void closeRepoManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeRepoManagerButtonActionPerformed
        repoManagerFrame.setVisible(false);
    }//GEN-LAST:event_closeRepoManagerButtonActionPerformed

    private void addRepoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRepoButtonActionPerformed
        //addRepoInput.getText()
    }//GEN-LAST:event_addRepoButtonActionPerformed

    private void closeErrorDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeErrorDialogActionPerformed
        errorDialog.setVisible(false);
    }//GEN-LAST:event_closeErrorDialogActionPerformed

    private void openRepoManagerAddRepoFrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openRepoManagerAddRepoFrameButtonActionPerformed
        repoManagerAddRepoFrame.setVisible(true);
    }//GEN-LAST:event_openRepoManagerAddRepoFrameButtonActionPerformed

    private void tempButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempButtonActionPerformed
        // ***** TEMP ERROR BUTTON *****
        Output.error("Something bad happened.");
        new LauncherGUI().switchToErrorTab();
    }//GEN-LAST:event_tempButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LauncherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LauncherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LauncherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LauncherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LauncherGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRepoButton;
    private javax.swing.JTextField addRepoInput;
    private javax.swing.JButton closeErrorDialog;
    private javax.swing.JButton closeRepoManagerButton;
    private javax.swing.JButton closeSettingsButton;
    private javax.swing.JDialog errorDialog;
    private javax.swing.JLabel errorDialogErrorText;
    private javax.swing.JScrollPane errorReportContainer;
    private javax.swing.JTextPane guiLogText;
    private javax.swing.JLabel info_text;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton launch;
    private javax.swing.ButtonGroup launch_selection;
    private javax.swing.JTabbedPane launcherTabs;
    private javax.swing.JPanel modpackPane;
    private javax.swing.JScrollPane modpackPaneContainer;
    private javax.swing.JButton openRepoManagerAddRepoFrameButton;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel rand;
    private javax.swing.JTextPane repoBox;
    private javax.swing.JFrame repoManagerAddRepoFrame;
    private javax.swing.JButton repoManagerButton;
    private javax.swing.JFrame repoManagerFrame;
    private javax.swing.JButton settingsButton;
    private javax.swing.JFrame settingsFrame;
    private javax.swing.JButton tempButton;
    private javax.swing.JTextField username;
    private javax.swing.JLabel ver;
    private javax.swing.JEditorPane webPane;
    private javax.swing.JScrollPane webPaneContainer;
    // End of variables declaration//GEN-END:variables
}
